server:
  port: 8090
  servlet:
    context-path: /

spring:
  #数据源
  datasource:

    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

#mybatis配置
mybatis:
  typeAliasesPackage: com.cfl.oneself.utils.entity
  mapperLocations: classpath:mapper/*.xml
  #configLocation: classpath:/mybatis-config.xml